#ifndef EAE6320_LOGGING_CONFIGURATION_H
#define EAE6320_LOGGING_CONFIGURATION_H
#define EAE6320_LOGGING_DEFAULTPATH "eae6320.log"
#ifdef _DEBUG
#define EAE6320_LOGGING_FLUSHBUFFERAFTEREVERYMESSAGE
#endif

#endif	
