#ifndef EAE6320_ENGINE_WINDOWS_INCLUDES_H
#define EAE6320_ENGINE_WINDOWS_INCLUDES_H

#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <Windows.h>
#undef NOMINMAX
#undef WIN32_LEAN_AND_MEAN

#endif	
