#ifndef EAE6320_GRAPHICS_CONFIGURATION_H
#define EAE6320_GRAPHICS_CONFIGURATION_H

#ifdef _DEBUG
	#define EAE6320_GRAPHICS_ISDEVICEDEBUGINFOENABLED
	#define EAE6320_GRAPHICS_AREDEBUGSHADERSENABLED
#endif

#endif

